# For external usage only
from .config import (
    COSMOS_DIR, KTNG_DIR, MODEL_DIR,
    PATH_TO_STD_NOISE, PATH_TO_MASK, PATH_TO_EXTENT, PATH_TO_PS,
    PATH_TO_TRAIN_VAL_DATASET, PATH_TO_TEST_DATASET, PATH_TO_CALIB_DATASET,
    PATH_TO_ZBINS, LEARNLETS_PRETRAINED_WEIGHTS_DIR,
    KEY_REPLACEMENT_DICT
)
