cosmos_dir: ~/Documents/Data/cosmos_v1.0/v1.0
trecs_dir: ~/Documents/Data/T-RECS
trec_file: catalogue_SFGs_complete_medium.fits
ktng_dir: ~/Documents/Data/kappaTNG_samples/kappaTNG
bin_file: kappa23.dat
png_file: kappa23.png