# Configuration file for data directories and file paths
#
# Parameters:
#   verbose: Boolean flag to enable verbose output when importing the wlmmuq library.
#   cosmos_dir: Path to the COSMOS data directory.
#   ktng_dir: Path to the kappaTNG data directory.
#   pycs_dir: Path to the cosmostat code directory.
#   pickle_dir: Path to the directory for pickled objects,
#       used in the Python script massmapping.py

verbose: true

cosmos_dir:
ktng_dir:
pycs_dir:
pickle_dir: