# Configuration file for data directories and file paths
#
# Parameters:
#   verbose: Boolean flag to enable verbose output when importing the wlmmuq library.
#   cosmos_dir: Path to the COSMOS data directory.
#   ktng_dir: Path to the kappaTNG data directory.

verbose: true

cosmos_dir: path/to/COSMOS/v1.0
ktng_dir: path/to/kappaTNG

path_to_std_noise: path/to/std_noise.pt
path_to_mask: path/to/mask.pt
path_to_ps: path/to/powerspectrum.pt

learnlets_pretrained_weights_dir: path/to/weights
